version: '3'
services:
  app:
    image: '192.168.226.131/propsoft-backend-side/backend:latest'
    volumes:
      - /var/www/html/propsoft-backend:/var/www/html/
    working_dir: /var/www/html
    networks:
      - laravel
    ports:
      - '8088:80'
 
networks:
  laravel:
